//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: mail.proto
// Note: requires additional types generated from: common.proto
namespace clientmsg
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UserOneMailContent")]
  public partial class UserOneMailContent : global::ProtoBuf.IExtensible
  {
    public UserOneMailContent() {}
    

    private uint _mailid = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"mailid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint mailid
    {
      get { return _mailid; }
      set { _mailid = value; }
    }

    private string _content = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"content", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string content
    {
      get { return _content; }
      set { _content = value; }
    }

    private clientmsg.enumMailType _type = clientmsg.enumMailType.enumMailType_Sys;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(clientmsg.enumMailType.enumMailType_Sys)]
    public clientmsg.enumMailType type
    {
      get { return _type; }
      set { _type = value; }
    }

    private uint _isdelete = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"isdelete", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint isdelete
    {
      get { return _isdelete; }
      set { _isdelete = value; }
    }

    private uint _isread = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"isread", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint isread
    {
      get { return _isread; }
      set { _isread = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UserOpenMail")]
  public partial class UserOpenMail : global::ProtoBuf.IExtensible
  {
    public UserOpenMail() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SendMailContent")]
  public partial class SendMailContent : global::ProtoBuf.IExtensible
  {
    public SendMailContent() {}
    
    private readonly global::System.Collections.Generic.List<clientmsg.UserOneMailContent> _mail_contents = new global::System.Collections.Generic.List<clientmsg.UserOneMailContent>();
    [global::ProtoBuf.ProtoMember(1, Name=@"mail_contents", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<clientmsg.UserOneMailContent> mail_contents
    {
      get { return _mail_contents; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DelMail")]
  public partial class DelMail : global::ProtoBuf.IExtensible
  {
    public DelMail() {}
    
    private readonly global::System.Collections.Generic.List<uint> _mail_ids = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(2, Name=@"mail_ids", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> mail_ids
    {
      get { return _mail_ids; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReadMail")]
  public partial class ReadMail : global::ProtoBuf.IExtensible
  {
    public ReadMail() {}
    
    private readonly global::System.Collections.Generic.List<uint> _mail_ids = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(1, Name=@"mail_ids", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> mail_ids
    {
      get { return _mail_ids; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UserSendMailByid")]
  public partial class UserSendMailByid : global::ProtoBuf.IExtensible
  {
    public UserSendMailByid() {}
    

    private ulong _remoteid = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"remoteid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong remoteid
    {
      get { return _remoteid; }
      set { _remoteid = value; }
    }

    private string _content = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"content", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string content
    {
      get { return _content; }
      set { _content = value; }
    }

    private clientmsg.enumMailType _type = clientmsg.enumMailType.enumMailType_Sys;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(clientmsg.enumMailType.enumMailType_Sys)]
    public clientmsg.enumMailType type
    {
      get { return _type; }
      set { _type = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UserSendMailByName")]
  public partial class UserSendMailByName : global::ProtoBuf.IExtensible
  {
    public UserSendMailByName() {}
    

    private string _remotename = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"remotename", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string remotename
    {
      get { return _remotename; }
      set { _remotename = value; }
    }

    private string _content = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"content", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string content
    {
      get { return _content; }
      set { _content = value; }
    }

    private clientmsg.enumMailType _type = clientmsg.enumMailType.enumMailType_Sys;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(clientmsg.enumMailType.enumMailType_Sys)]
    public clientmsg.enumMailType type
    {
      get { return _type; }
      set { _type = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"enumMailType")]
    public enum enumMailType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"enumMailType_Sys", Value=1)]
      enumMailType_Sys = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"enumMailType_RequestAddFriend", Value=2)]
      enumMailType_RequestAddFriend = 2
    }
  
}